sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ssushma2141/docker-react -f Dockerfile.dev .

script:
  - docker run ssushma2141/docker-react npm run test -- --coverage
